name: Deployment (Container)
on:
  push:
    branches:
      - main
      - dev
env:
  CACHE_KEY: node-deps
  MONGODB_DB_NAME: gha-demo
jobs:
  test:
    environment: testing
    runs-on: ubuntu-latest
    #container: node:16 #image to use #to run your jobs on custom container define the following keyword
      #image: node:16 #mcr.microsoft.com/playwright:v1.25.0-focal
      #The commented way of calling is used if we have to pass further information. like the environment variables
      #env: 
    env:
      MONGODB_CONNECTION_PROTOCOL: mongodb #mongodb+srv
      MONGODB_CLUSTER_ADDRESS: 127.0.0.1:27017  #If contianer is not running and only services
      MONGODB_USERNAME: root #As meniod below #on Atlae: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_PASSWORD: example #On atlas${{ secrets.MONGODB_PASSWORD }}
      PORT: 8080
    services: #TO run services(belog to a job) in a created container this is the proces and keyword. Service connection can also run without contianer defined.
      mongodb: #here name has to be aidentifier
        image: mongo #here we add service specific keys
        ports:
          - 27017:27017
        env: 
          MONGO_INITDB_ROOT_USERNAME: root #based on docker mongodb image
          MONGO_INITDB_ROOT_PASSWORD: example      
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ env.CACHE_KEY }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT # requires MongoDB Atlas to accept requests from anywhere!
      - name: Run tests
        run: npm test
      - name: Output information
        run: |
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        env:
          PORT: 3000
        run: |        
          echo "MONGODB_DB_NAME: $MONGODB_DB_NAME"
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"
          echo "${{ env.PORT }}"
